version: '3.8'

services:
  backend:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - PORT=8000
      - OPENROUTER_MODEL=gpt-3.5-turbo
      # Add other environment variables as needed
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload 